name: Build Doc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64

    - name: Clone pyobs
      uses: actions/checkout@v2
      with:
        path: pyobs

    - name: Install pyobs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy sphinx
        pip install ./pyobs

    - name: Deploy doc
      uses: mbruno46/deploy-sphinx-doc@main
      with:
       path: doc
       doc-branch: 'documentation'
